"""Public Volcano SDK facade."""

from .client import VolcanoClient
from .errors import (
    AuthenticationError,
    ConflictError,
    NotFoundError,
    RateLimitedError,
    ServerError,
    SessionChangedError,
    TransportError,
    ValidationError,
    VolcanoError,
)
from .models import (
    AuthChangeEvent,
    AuthSession,
    AuthStateCallback,
    AuthSubscription,
    EmailChangeResult,
    LinkedOAuthProvider,
    LockLease,
    OAuthProviderName,
    OAuthProviderTokenStatus,
    Session,
    SessionPage,
    SignUpResult,
    StorageObject,
    StoragePage,
    User,
)

__all__ = [
    "AuthChangeEvent",
    "AuthSession",
    "AuthStateCallback",
    "AuthSubscription",
    "AuthenticationError",
    "ConflictError",
    "EmailChangeResult",
    "LinkedOAuthProvider",
    "LockLease",
    "NotFoundError",
    "OAuthProviderName",
    "OAuthProviderTokenStatus",
    "RateLimitedError",
    "ServerError",
    "Session",
    "SessionChangedError",
    "SessionPage",
    "SignUpResult",
    "StorageObject",
    "StoragePage",
    "TransportError",
    "User",
    "ValidationError",
    "VolcanoClient",
    "VolcanoError",
]
