"""Internal transport boundary around the generated OpenAPI client."""

from ._transport_auth_account import AuthAccountTransport
from ._transport_auth_identity import AuthIdentityTransport
from ._transport_database import DatabaseTransport
from ._transport_execution import ExecutionTransport
from ._transport_locks import LocksTransport
from ._transport_response import invoke, invoke_async, response_payload
from ._transport_storage import StorageTransport
from ._transport_types import (
    ERROR_TYPES_BY_STATUS,
    HTTP_CONFLICT,
    HTTP_CREATED,
    HTTP_NOT_FOUND,
    HTTP_OK,
    HTTP_RATE_LIMITED,
    HTTP_SERVER_ERROR_MAX,
    HTTP_SERVER_ERROR_MIN,
    HTTP_UNAUTHORIZED,
    AsyncDatabaseSelectTransport,
    AuthCallOAuthAPITransport,
    AuthCancelEmailChangeTransport,
    AuthConfirmEmailChangeTransport,
    AuthConfirmEmailTransport,
    AuthConvertAnonymousTransport,
    AuthDeleteAllMySessionsTransport,
    AuthDeleteMySessionTransport,
    AuthForgotPasswordTransport,
    AuthGetMySessionsTransport,
    AuthGetOAuthProviderTokenTransport,
    AuthGetUserTransport,
    AuthLinkOAuthProviderTransport,
    AuthListOAuthProvidersTransport,
    AuthLogoutTransport,
    AuthOAuthAuthorizationURLTransport,
    AuthOAuthExchangeTransport,
    AuthRefreshOAuthProviderTokenTransport,
    AuthRefreshTransport,
    AuthRequestEmailChangeTransport,
    AuthResendConfirmationTransport,
    AuthResetPasswordTransport,
    AuthSignUpAnonymousTransport,
    AuthSignUpTransport,
    AuthUnlinkOAuthProviderTransport,
    AuthUpdateUserTransport,
    DurableExecutionListRequest,
    StorageUploadPartRequest,
    StorageUploadSessionReference,
    StorageUploadSessionRequest,
    Transport,
    TransportResponse,
)

__all__ = [
    "ERROR_TYPES_BY_STATUS",
    "HTTP_CONFLICT",
    "HTTP_CREATED",
    "HTTP_NOT_FOUND",
    "HTTP_OK",
    "HTTP_RATE_LIMITED",
    "HTTP_SERVER_ERROR_MAX",
    "HTTP_SERVER_ERROR_MIN",
    "HTTP_UNAUTHORIZED",
    "AsyncDatabaseSelectTransport",
    "AuthCallOAuthAPITransport",
    "AuthCancelEmailChangeTransport",
    "AuthConfirmEmailChangeTransport",
    "AuthConfirmEmailTransport",
    "AuthConvertAnonymousTransport",
    "AuthDeleteAllMySessionsTransport",
    "AuthDeleteMySessionTransport",
    "AuthForgotPasswordTransport",
    "AuthGetMySessionsTransport",
    "AuthGetOAuthProviderTokenTransport",
    "AuthGetUserTransport",
    "AuthLinkOAuthProviderTransport",
    "AuthListOAuthProvidersTransport",
    "AuthLogoutTransport",
    "AuthOAuthAuthorizationURLTransport",
    "AuthOAuthExchangeTransport",
    "AuthRefreshOAuthProviderTokenTransport",
    "AuthRefreshTransport",
    "AuthRequestEmailChangeTransport",
    "AuthResendConfirmationTransport",
    "AuthResetPasswordTransport",
    "AuthSignUpAnonymousTransport",
    "AuthSignUpTransport",
    "AuthUnlinkOAuthProviderTransport",
    "AuthUpdateUserTransport",
    "DurableExecutionListRequest",
    "GeneratedTransport",
    "StorageUploadPartRequest",
    "StorageUploadSessionReference",
    "StorageUploadSessionRequest",
    "Transport",
    "TransportResponse",
    "invoke",
    "invoke_async",
    "response_payload",
]


class GeneratedTransport(
    AuthIdentityTransport,
    AuthAccountTransport,
    DatabaseTransport,
    StorageTransport,
    ExecutionTransport,
    LocksTransport,
):
    """Compose typed generated operations behind the stable SDK transport."""
