from collections.abc import Callable
from dataclasses import dataclass
from enum import Enum, StrEnum
from typing import Generic, TypeVar

from aws_durable_execution_sdk_python.retries import RetryDecision
from aws_durable_execution_sdk_python.serdes import SerDes
from aws_durable_execution_sdk_python.types import SummaryGenerator

_T = TypeVar("_T")

@dataclass(frozen=True)
class Duration:
    seconds: int = ...
    def to_seconds(self) -> int: ...
    @classmethod
    def from_seconds(cls, value: float) -> Duration: ...
    @classmethod
    def from_minutes(cls, value: float) -> Duration: ...
    @classmethod
    def from_hours(cls, value: float) -> Duration: ...
    @classmethod
    def from_days(cls, value: float) -> Duration: ...

class NestingType(Enum):
    NESTED = "NESTED"
    FLAT = "FLAT"

class BatchItemStatus(Enum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    STARTED = "STARTED"

class CompletionOutcome(Enum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"

@dataclass(frozen=True)
class CompletionDecision:
    complete: bool
    outcome: CompletionOutcome | None = ...

@dataclass(frozen=True)
class CompletionItemStatus:
    index: int
    name: str | None = ...
    status: BatchItemStatus | None = ...

@dataclass(frozen=True)
class CompletionStatus:
    success_count: int
    failure_count: int
    completed_count: int
    total_count: int
    items: tuple[CompletionItemStatus, ...] = ...

@dataclass(frozen=True)
class CompletionConfig:
    min_successful: int | None = ...
    tolerated_failure_count: int | None = ...
    tolerated_failure_percentage: int | float | None = ...
    should_complete: Callable[[CompletionStatus], CompletionDecision] | None = ...
    @staticmethod
    def first_successful() -> CompletionConfig: ...
    @staticmethod
    def all_completed() -> CompletionConfig: ...
    @staticmethod
    def all_successful() -> CompletionConfig: ...

@dataclass(frozen=True)
class ParallelConfig:
    max_concurrency: int | None = ...
    completion_config: CompletionConfig = ...
    serdes: SerDes[object] | None = ...
    item_serdes: SerDes[object] | None = ...
    summary_generator: SummaryGenerator[object] | None = ...
    nesting_type: NestingType = ...

@dataclass(frozen=True)
class MapConfig(Generic[_T]):
    max_concurrency: int | None = ...
    completion_config: CompletionConfig = ...
    serdes: SerDes[object] | None = ...
    item_serdes: SerDes[object] | None = ...
    summary_generator: SummaryGenerator[object] | None = ...
    nesting_type: NestingType = ...
    item_namer: Callable[[_T, int], str] | None = ...

@dataclass(frozen=True)
class ParallelBranch(Generic[_T]):
    func: Callable[[object], _T]
    name: str | None = ...
    def __call__(self, context: object) -> _T: ...

class StepSemantics(Enum):
    AT_MOST_ONCE_PER_RETRY = "AT_MOST_ONCE_PER_RETRY"
    AT_LEAST_ONCE_PER_RETRY = "AT_LEAST_ONCE_PER_RETRY"

@dataclass(frozen=True)
class StepConfig:
    retry_strategy: Callable[[Exception, int], RetryDecision] | None = ...
    step_semantics: StepSemantics = ...
    serdes: SerDes[object] | None = ...

class JitterStrategy(StrEnum):
    NONE = "NONE"
    FULL = "FULL"
    HALF = "HALF"
    def apply_jitter(self, delay: float) -> float: ...
    def finalize_delay(self, base_delay: float) -> int: ...
