import re
from collections.abc import Callable
from dataclasses import dataclass

from aws_durable_execution_sdk_python.config import Duration, JitterStrategy

@dataclass
class RetryDecision:
    should_retry: bool
    delay: Duration
    @property
    def delay_seconds(self) -> int: ...
    @classmethod
    def retry(cls, delay: Duration) -> RetryDecision: ...
    @classmethod
    def no_retry(cls) -> RetryDecision: ...

@dataclass
class RetryStrategyConfig:
    max_attempts: int = ...
    initial_delay: Duration = ...
    max_delay: Duration = ...
    backoff_rate: int | float = ...
    jitter_strategy: JitterStrategy = ...
    retryable_errors: list[str | re.Pattern[str]] | None = ...
    retryable_error_types: list[type[Exception]] | None = ...
    @property
    def initial_delay_seconds(self) -> int: ...
    @property
    def max_delay_seconds(self) -> int: ...

def create_retry_strategy(
    config: RetryStrategyConfig | None = ...,
) -> Callable[[Exception, int], RetryDecision]: ...
